language: scala
sudo: false
jdk: openjdk8

jobs:
  include:
    - stage: test
      name : "metarules"
      script:
        - sbt test
        - ./compileAllMetarules.sh

    - stage: test
      name : "controller-compiler"
      # download and run the controller compiler in non-interactive mode with default settings
      before_script:
        - wget https://www.dropbox.com/s/gqsv3t5w36ywk0j/NAMControllerCompiler_1.2.1.zip -O NAMControllerCompiler.zip
        - unzip NAMControllerCompiler.zip -d compiler
      script:
        - cd compiler && java -jar NAMControllerCompiler.jar ../Controller ../target 1 0 0xFFFF 0x01FF 0x01FF 0x01FF 0x001C 0x001C 0x0008 0x0001 0xFFFF

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
